Exploring the survey

In [129]:
# Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('SurveyFull.csv')

Get rid of useless rows and - title and empty ones

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

In [130]:
dataset = dataset.iloc[8:,:]

Get rid of irrelevant columns

In [131]:
dataset = dataset.iloc[0:-2,10:]

In [132]:
datasetTmp = dataset.values

In [133]:
datasetTmp[0]

array(['Right Handed', 'Evening Person', 'Yes', 'No', 'Yes', 'Yes',
       'Science Fiction', 'Neither', 'Yes', "Don't care", 'No', 'No',
       'Yes', 'No', 'No'], dtype=object)

Just get the columns for independent variable

In [134]:
X = dataset.iloc[:,0:2].values

In [135]:
X

array([['Right Handed', 'Evening Person'],
       ['Right Handed', 'Morning Person'],
       ['Right Handed', 'Evening Person'],
       ['Right Handed', 'Evening Person'],
       ['Right Handed', 'Morning Person'],
       ['Right Handed', 'Evening Person'],
       ['Right Handed', 'Morning Person'],
       ['Right Handed', 'Morning Person'],
       ['Right Handed', 'Morning Person'],
       ['Right Handed', 'Morning Person'],
       ['Right Handed', 'Evening Person'],
       ['Right Handed', 'Evening Person'],
       ['Right Handed', 'Morning Person'],
       ['Right Handed', 'Evening Person'],
       ['Left Handed', 'Evening Person'],
       ['Right Handed', 'Morning Person'],
       ['Right Handed', 'Evening Person'],
       ['Right Handed', 'Evening Person'],
       ['Right Handed', 'Evening Person'],
       ['Right Handed', 'Morning Person'],
       ['Right Handed', 'Evening Person'],
       ['Right Handed', 'Morning Person'],
       ['Right Handed', 'Morning Person'],
       ['Rig

Get the dependent column

In [136]:
y = dataset.iloc[:,-1].values

In [137]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
X[:, 1] = labelencoder_X.fit_transform(X[:, 1])

In [138]:
X

array([[1, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1]], dtype=object)

In [139]:
#not needed unless more than 2 states
#onehotencoder = OneHotEncoder(categorical_features = [0])
#X = onehotencoder.fit_transform(X).toarray()

In [140]:
X

array([[1, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 0],
       [1, 1]], dtype=object)

In [141]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)


In [142]:
len(X_train)

23

In [143]:
len(X_test)

8

In [144]:
# Feature Scaling - Not needed due to using only 1 and 0
#from sklearn.preprocessing import StandardScaler
#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

In [145]:
# Fitting classifier to the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)


In [146]:
cm

array([[7, 0],
       [1, 0]])