In [80]:
from flask import Flask, jsonify, request
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [ ]:
app = Flask(__name__)
@app.route('/dataselect', methods = ['GET'])
def ingest():
    independentVar = request.args.get('independent')
    dependentVar = request.args.get('dependent')
    if not dependentVar :
        dependentVar = "Nothing"
    message = "I: " + independentVar + " D: " + dependentVar
    
    """
    dataset = pd.read_csv('data/survey.csv')

    # get rid of leading columns
    dataset = dataset.iloc[1:,10:].values

    #sample set
    selString = "2,1,3"
    selArray = selString.split(",")

    #change to set of integers (no repeats) in reverse order
    iSet = set()
    for i in selArray:
        iSet.add(int(i))
    length = len(dataset[0])  
    for i in reversed(range(0,length)):
       if i not in iSet:
        dataset = np.delete(dataset,i,1)

    #change categorical data to 1/0 columns
    labelencoder = LabelEncoder()
    catFeatures = {}
    for i in range(0, len(dataset[0])):
        try:
            #test to see if it is an integer
            int(dataset[:,i][0])
        # Not an integer
        except ValueError:
            #determine length
            if( len(set(dataset[:,i])) > 2):                
                dataset[:,i] = labelencoder.fit_transform(dataset[:,i])
                catFeatures.update({i:len(set(dataset[:,i]))})

            else:
                dataset[:,i] = labelencoder.fit_transform(dataset[:,i]) 

    catFeaturesArray = []
    for key, value in catFeatures.items():
        catFeaturesArray.append(key)
    onehotencoder = OneHotEncoder(categorical_features = catFeaturesArray)
    dataset = onehotencoder.fit_transform(dataset).toarray()

    #must delete one column for each categorical data set
    delCol = 0
    for key, value in catFeatures.items():
        dataset = np.delete(dataset, delCol, 1)
    #adjusts for the disappearing column from above
    delCol += value -1

    # Must scale the data
    # Feature Scaling

    sc = StandardScaler()
    dataset = sc.fit_transform(dataset)

    #save data
    np.save('data/MachineLine2.npy', dataset)

    datasetNew = np.load('data/MachineLine2.npy')

    if( np.array_equal(dataset, datasetNew)):
        message = "Exact Copy"
    else:
        message = "Incorrect Data Copy"
            
    """   
    return message, 200
    
#Running the app

print('starting server...')
app.run(host = '0.0.0.0', port = 5000)

 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)


starting server...


192.168.2.50 - - [19/Dec/2018 23:44:50] "GET /dataselect?independent=1,2,3&dependent= HTTP/1.1" 200 -


In [61]:
dataset = pd.read_csv('data/survey.csv')

# get rid of leading columns
dataset = dataset.iloc[1:,10:].values
print("Dataset len: ", len(dataset[0]))

#sample set
selString = "2,1,3"
selArray = selString.split(",")

#change to set of integers (no repeats) in reverse order
iSet = set()
for i in selArray:
    iSet.add(int(i))
length = len(dataset[0])  
for i in reversed(range(0,length)):
   if i not in iSet:
    print("Deleting: ", i)
    dataset = np.delete(dataset,i,1)
   else:
    print("Not deleting: ", i)
print("LENGTH: ", len(dataset[0]))

#change categorical data to 1/0 columns
labelencoder = LabelEncoder()
catFeatures = {}
for i in range(0, len(dataset[0])):
    try:
        print( int(dataset[:,i][0]))
    # Not an integer
    except ValueError:
        print("Not Integer")
        #determine length
        if( len(set(dataset[:,i])) > 2):
            #print(set(dataset[:,i]))
            print("3 or more Array)")
            
            print(dataset[:,i])
            dataset[:,i] = labelencoder.fit_transform(dataset[:,i])
            print(dataset[:,i])
            catFeatures.update({i:len(set(dataset[:,i]))})

        else:
            print("2 element array")
            # Encoding categorical data

            
            print(dataset[:,i])
            dataset[:,i] = labelencoder.fit_transform(dataset[:,i])
            print(dataset[:,i])
 

catFeaturesArray = []
for key, value in catFeatures.items():
    catFeaturesArray.append(key)
onehotencoder = OneHotEncoder(categorical_features = catFeaturesArray)
print("CatFeatures: ", catFeatures)
dataset = onehotencoder.fit_transform(dataset).toarray()
print(dataset)

#must delete one column for each categorical data set
delCol = 0
for key, value in catFeatures.items():
    print("Delete Column: ", delCol)
    dataset = np.delete(dataset, delCol, 1)
    #adjusts for the disappearing column from above
    delCol += value -1
print(dataset)

# Must scale the data
# Feature Scaling

sc = StandardScaler()
dataset = sc.fit_transform(dataset)
print(dataset)

#save data
np.save('data/MachineLine2.npy', dataset)

datasetNew = np.load('data/MachineLine2.npy')

if( np.array_equal(dataset, datasetNew)):
    print("Exact Copy")
            


Dataset len:  15
Deleting:  14
Deleting:  13
Deleting:  12
Deleting:  11
Deleting:  10
Deleting:  9
Deleting:  8
Deleting:  7
Deleting:  6
Deleting:  5
Deleting:  4
Not deleting:  3
Not deleting:  2
Not deleting:  1
Deleting:  0
LENGTH:  3
Not Integer
2 element array
['Cat Person' 'Dog Person' 'Dog Person' 'Dog Person' 'Cat Person'
 'Dog Person' 'Dog Person' 'Dog Person']
[0 1 1 1 0 1 1 1]
Not Integer
3 or more Array)
['Windows' 'Windows' 'Linux' 'Windows' 'Linux' 'Linux' 'Linux' 'Mac']
[2 2 0 2 0 0 0 1]
Not Integer
2 element array
['With Others' 'Individual (On my own)' 'Individual (On my own)'
 'Individual (On my own)' 'With Others' 'With Others'
 'Individual (On my own)' 'With Others']
[1 0 0 0 1 1 0 1]
CatFeatures:  {1: 3}
[[ 0.  0.  1.  0.  1.]
 [ 0.  0.  1.  1.  0.]
 [ 1.  0.  0.  1.  0.]
 [ 0.  0.  1.  1.  0.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  1.  1.]
 [ 1.  0.  0.  1.  0.]
 [ 0.  1.  0.  1.  1.]]
Delete Column:  0
[[ 0.  1.  0.  1.]
 [ 0.  1.  1.  0.]
 [ 0.  0.  1.  0.]
 [ 

In [55]:
 
import numpy as np
import pandas as pd
dataset = pd.read_csv('data/survey.csv')

# get rid of leading columns
dataset = dataset.iloc[1:,10:].values
print("Dataset len: ", len(dataset[0]))

selString = "2,1,3"
selArray = selString.split(",")

#change to set of integers (no repeats) in reverse order
iSet = set()
for i in selArray:
    iSet.add(int(i))
length = len(dataset[0])  
for i in reversed(range(0,length)):
   if i not in iSet:
    print("Deleting: ", i)
    dataset = np.delete(dataset,i,1)
   else:
    print("Not deleting: ", i)
dataset

Dataset len:  15
Deleting:  14
Deleting:  13
Deleting:  12
Deleting:  11
Deleting:  10
Deleting:  9
Deleting:  8
Deleting:  7
Deleting:  6
Deleting:  5
Deleting:  4
Not deleting:  3
Not deleting:  2
Not deleting:  1
Deleting:  0


array([['Cat Person', 'Windows', 'With Others'],
       ['Dog Person', 'Windows', 'Individual (On my own)'],
       ['Dog Person', 'Linux', 'Individual (On my own)'],
       ['Dog Person', 'Windows', 'Individual (On my own)'],
       ['Cat Person', 'Linux', 'With Others'],
       ['Dog Person', 'Linux', 'With Others'],
       ['Dog Person', 'Linux', 'Individual (On my own)'],
       ['Dog Person', 'Mac', 'With Others']], dtype=object)

In [19]:
import numpy as np
import pandas as pd
dataset = pd.read_csv('data/survey.csv')

# get rid of leading columns
dataset = dataset.iloc[1:,10:].values
print("Dataset len: ", len(dataset[0]))

dataset2 = np.append((dataset[1,:] ,dataset[2:]),  1)
dataset2

Dataset len:  15


array([ array(['Science Fiction', 'Dog Person', 'Windows',
       'Individual (On my own)', 'Star Wars', 'No', 'Yes', 'No', '12', '0',
       '0', '11', '2', 'No', '30 to 45 Years Old'], dtype=object),
       array([['Science Fiction', 'Dog Person', 'Linux', 'Individual (On my own)',
        'Star Trek', 'No', 'Yes', 'No', '3', '20', '16', '6', '8', 'Yes',
        'Over 45 Years Old'],
       ['Science Fiction', 'Dog Person', 'Windows',
        'Individual (On my own)', 'Star Trek', 'Yes', 'Yes', 'Yes', '10',
        '45', '2', '8', '15', 'No', '30 to 45 Years Old'],
       ['Comedy', 'Cat Person', 'Linux', 'With Others', 'Star Trek', 'Yes',
        'Yes', 'No', '30', '40', '5', '30', '5', 'No',
        'Less than 30 Years Old'],
       ['Adventure', 'Dog Person', 'Linux', 'With Others', 'Star Wars',
        'Yes', 'Yes', 'Yes', '10', '10', '8', '12', '2', 'Yes',
        'Over 45 Years Old'],
       ['Romance', 'Dog Person', 'Linux', 'Individual (On my own)',
        'Star Trek', 'Yes'

In [27]:
x = dataset[:,1]
x


array(['Cat Person', 'Dog Person', 'Dog Person', 'Dog Person',
       'Cat Person', 'Dog Person', 'Dog Person', 'Dog Person'], dtype=object)

In [31]:
len(dataset[0])

15

In [30]:
np.delete(dataset,0,1)

array([['Cat Person', 'Windows', 'With Others', 'Star Trek', 'Yes', 'No',
        'Yes', '4', '15', '1', '10', '2', 'No', '30 to 45 Years Old'],
       ['Dog Person', 'Windows', 'Individual (On my own)', 'Star Wars',
        'No', 'Yes', 'No', '12', '0', '0', '11', '2', 'No',
        '30 to 45 Years Old'],
       ['Dog Person', 'Linux', 'Individual (On my own)', 'Star Trek', 'No',
        'Yes', 'No', '3', '20', '16', '6', '8', 'Yes', 'Over 45 Years Old'],
       ['Dog Person', 'Windows', 'Individual (On my own)', 'Star Trek',
        'Yes', 'Yes', 'Yes', '10', '45', '2', '8', '15', 'No',
        '30 to 45 Years Old'],
       ['Cat Person', 'Linux', 'With Others', 'Star Trek', 'Yes', 'Yes',
        'No', '30', '40', '5', '30', '5', 'No', 'Less than 30 Years Old'],
       ['Dog Person', 'Linux', 'With Others', 'Star Wars', 'Yes', 'Yes',
        'Yes', '10', '10', '8', '12', '2', 'Yes', 'Over 45 Years Old'],
       ['Dog Person', 'Linux', 'Individual (On my own)', 'Star Trek',
        'Y